### ISSUE TITLE
Ruby 2.7 compatibility

### ISSUE THREAD

**Issue by zormandi** [kyledecot/app_store_connect#111]
Hi,

**Is your feature request related to a problem? Please describe.**

We're just starting to use your gem in our project which still runs on Ruby 2.7. I see that in your last commit you set the required Ruby version to >= 3.1 which obviously won't work for us. Going through the commit (at a quick glance) I think the only feature you're using that requires 3.1 is the hash value omission and not using that would be a very small price to pay for keeping this gem usable to folks on older Ruby versions.

**Describe the solution you'd like**

Would you be okay with us creating a PR for Ruby 2.7 compatibility?

**Comment by kyledecot** [comment]
@zormandi – yes that would be awesome 🎉
