### ISSUE TITLE
Can we remove tracking?

### ISSUE THREAD

**Issue by zormandi** [kyledecot/app_store_connect#121]
Hi,

This is more of a question rather than a feature request. We've added some more endpoints (phased release management, update build) to our fork of the project but for security compliance reasons we had to remove the dependency on MixPanel (even though we see that its use can be disabled). Would you be interested in merging this change? If yes then I can quickly open a PR for it. If not then that's a bit more complicated. We'd still love to contribute but it's going to be a problem repeating all of our PRs in both projects. 😞 

Thanks,
Z

**Comment by kyledecot** [comment]
Yes–this can be safely removed 🔥

**Comment by zormandi** [comment]
Cool, thanks. 👍
