### ISSUE TITLE
execution expired (Net::OpenTimeout)

### ISSUE THREAD

**Issue by huainanzi** [kyledecot/app_store_connect#128]
I get execution expired (Net::OpenTimeout) error, Where can I set the please request timeout

**Comment by kyledecot** [comment]
The default for net/http is 60 seconds which seems like it should be more than enough time. 

Mind providing some code for context?

Also, do calls ever succeed (is the timeout consistent)?

**Comment by huainanzi** [comment]
> The default for net/http is 60 seconds which seems like it should be more than enough time.
> 
> Mind providing some code for context?
> 
> Also, do calls ever succeed (is the timeout consistent)?
> 
> To answer your question though, there is currently no configurable option for this and would need to be added to 'Request'

I want to get the expiration of testfight for all apps under the account
like this：
app_store_connect = AppStoreConnect::Client.new
    apps = app_store_connect.apps[:data]
    apps.each { |app|
        app_name = app[:attributes][:name]
        app_id = app[:id]
        #
        beta_groups = app_store_connect.app_beta_groups(id:app_id)[:data]
        unless beta_groups.empty?
            beta_groups.each { |beta_group|
                unless beta_group[:attributes][:is_internal_group]
                    beta_group_id = beta_group[:id]
                    beta_builds = app_store_connect.beta_group_builds(id:beta_group_id)[:data]
                    unless beta_builds.empty?
                        beta_builds.each { |build|
                            
                        }
                    end
                end
            }
        end
    } 
I don't know if it's the appstore's api limit or the ruby  timeout problem

**Comment by kyledecot** [comment]
@huainanzi did you make any headway when attempting to debug this issue?

**Comment by huainanzi** [comment]
May be the network is unstable，I add require 'resolv-replace',
Currently not reproduced

**Comment by kyledecot** [comment]
Since you have not been able to reproduce this issue I'm going to close for now but please feel to reopen if it needed 🐛
