### ISSUE TITLE
require 'app_store_connect' failed

### ISSUE THREAD

**Issue by guozanhua** [kyledecot/app_store_connect#78]
**Describe the bug**
Create a test.rb, only require app_store_connect as below:

require 'app_store_connect'

**To Reproduce**
1. create test.rb, only include "require 'app_store_connect'"
2. ruby test.rb
3. error occur as below:

/Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/attributes.rb:22:in `block (2 levels) in <module:Attributes>': private method `define_method' called for #<Class:0x00007fe4122c1570> (NoMethodError)
Did you mean?  define_singleton_method
               redefine_method
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/attributes.rb:19:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/attributes.rb:19:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/attributes.rb:19:in `block in <module:Attributes>'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/concern.rb:120:in `class_eval'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/concern.rb:120:in `append_features'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/data.rb:14:in `include'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/data.rb:14:in `block (2 levels) in <module:Data>'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/data.rb:13:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/data.rb:13:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/object/data.rb:13:in `block in <module:Data>'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/concern.rb:120:in `class_eval'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/concern.rb:120:in `append_features'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/create_request.rb:6:in `include'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/create_request.rb:6:in `inherited'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/bundle_id_create_request.rb:6:in `<module:AppStoreConnect>'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect/bundle_id_create_request.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/app_store_connect-0.14.0/lib/app_store_connect.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from test.rb:2:in `<main>'

**Comment by kyledecot** [comment]
@guozanhua this has been fixed in `0.16.0` and published to rubygems.org–thanks for reporting this and sorry it took so long to get a fix.
