### ISSUE TITLE
Key Not Found :schema

### ISSUE THREAD

**Issue by abgier-blitzm** [kyledecot/app_store_connect#84]
**Describe the bug**
/gems/app_store_connect-0.16.0/lib/app_store_connect/client/registry.rb:11:in `fetch': [!] key not found: :schema (KeyError)

**To Reproduce**
```
        AppStoreConnect.config = {
          issuer_id: issuer_id,
          key_id: key_id,
          private_key: api_key
        }
        app_store_connect = AppStoreConnect::Client.new
```
**Expected behavior**
Initiailise a new Client object

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Ruby: 2.6.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kyledecot** [comment]
Thanks for reporting this @abgier-blitzm–this was fixed in #85 and release to both Rubygems and Github Package Registry as `v0.17.0`
