### ISSUE TITLE
How do I set GET query parameters?

### ISSUE THREAD

**Issue by abgier-blitzm** [kyledecot/app_store_connect#90]
https://developer.apple.com/documentation/appstoreconnectapi/list_and_download_profiles#query-parameters

Lets say I want to call `GET https://api.appstoreconnect.apple.com/v1/profiles` and filter by `bundleIds`.

How would I do this? Is it still done from `app_store_connect.profiles`?

**Comment by kyledecot** [comment]
Both URL and query parameters are passed as the first argument. For example:

```ruby
app_store_connect.profiles(limit: 1)
```

If you want to filter by Bundle ID (`com.kyledecot.Example`) I think you'd need to do something like:

```ruby
require 'app_store_connect'

app_store_connect = AppStoreConnect::Client.new
bundle_id_identifier = 'com.kyledecot.Example'

response = app_store_connect.profiles(
  include: 'bundleId',
  fields: {
    profiles: 'bundleId',
    bundleIds: 'identifier'
  }
)

bundle_id = response['included']
            .select { |i| i['type'] == 'bundleIds' }
            .detect({}) { |i| i.dig('attributes', 'identifier') == bundle_id_identifier }

profiles = response['data'].select do |data|
  bundle_id['id'] == data.dig('relationships', 'bundleId', 'data', 'id')
end
```
